version: '3.8'

services:
  app:
    image: iczp/ocr-api:0.0.5

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    environment:
      # 这里可以显式地添加环境变量，但通常不需要这样做，因为.env中的变量会自动被加载
      # API_KEY: ${API_KEY}  # 这行是多余的，除非你想覆盖.env中的值或添加注释
      NODE_ENV: production
    env_file:
      - .env # 这行是可选的，因为docker-compose会自动查找同目录下的.env文件
